<div class="topbar">
	<div class="fill">
    	<div class="container">
        	<h3><a href="#">AdminControl</a></h3>
          	<ul class="nav">
            <li><?php echo link_to('inicio/','Inicio'); ?></li>
            <li><?php echo link_to('usuario/login','Inicio de sesion');?></li>
            <li><?php echo link_to('usuario/registro/','Nuevo Usuario'); ?></li>
          </ul>
        </div>
      </div>
    </div>