<div class="topbar">
	<div class="fill">
    	<div class="container">
        	<h3><a href="#">Nombre Empresa</a></h3>
          	<ul class="nav">
            <li><?php echo link_to('inicio/','Inicio'); ?></li>
            <li><?php echo link_to('usuario/perfil','Perfil');?></li>
            <li><?php echo link_to('ventas/','Ventas'); ?></li>
            <li><?php echo link_to('rrhh','Recursos Humanos'); ?></li>
            <li><?php echo link_to('bodega/','Bodega'); ?></li>
            <li><?php echo link_to('administrar/','Administrar');?></li>
            <li><?php echo link_to('usuario/logout','Cerrar Sesion'); ?></li>
          </ul>
        </div>
      </div>
    </div>