<h3>Empresa</h3>
<?php echo link_to('producto/mostrar','Info. Basica',''); ?><br>
<?php echo link_to('producto/agregar','Agregar Noticia',''); ?><br>
<?php echo link_to('producto/agregar','Listar Noticias',''); ?><br>
<h3>Usuarios</h3>
<?php echo link_to('bodega/agregar','Agregar Usuario',''); ?><br>
<?php echo link_to('bodega/administrar','Listar Usuarios',''); ?><br>
<?php echo link_to('bodega/mostrar','Ver Estadisticas',''); ?><br>
<h3>Bodega</h3>
<?php echo link_to('bodega/mostrar','Agregar Bodega/s',''); ?><br>
<?php echo link_to('bodega/mostrar','Ver/Modificar Bodega/s',''); ?><br>
<?php echo link_to('bodega/agregar','Tipos de Categorias',''); ?><br>
<?php echo link_to('bodega/administrar','Tipos de Productos',''); ?><br>
<?php echo link_to('bodega/mostrar','Informes',''); ?><br>
<?php echo link_to('bodega/mostrar','Informes',''); ?><br>